name: flutter_v2ray
description: A Flutter plugin for connecting to V2Ray servers via VLESS links on both Android and iOS platforms
version: 0.0.1
homepage: https://github.com/username/flutter_v2ray

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_v2ray
        pluginClass: FlutterV2rayPlugin
      ios:
        pluginClass: FlutterV2rayPlugin
  assets:
    - assets/v2ray/
